### PR TITLE
Feature/usb cam node

### PR DESCRIPTION
**Pull request by hello-fazil**
This PR introduces a custom [USB Cam node](https://github.com/hello-robot/stretch_ros2/blob/dca394dfad124281cbf3ceaa373b81f2266f1cb4/stretch_core/stretch_core/usb_cam.py) that uses OpenCV python to access USB camera feed from the given video port and publish it.  The following parameters can be modified or set to use the node:
- `camera_port` = Video device port E.g. /dev/video3
- `publish_topic` = Image topic to publish E.g. /usb_cam/image_raw
- Optional Camera Properties that can be applied:
`format`, `size`, `fps`, `brightness`, `contrast`, `saturation`, `hue`, `gamma`, `gain`, `white_balence_temp`, `sharpness`, `backlight`
See [navigation_camera.launch.py](https://github.com/hello-robot/stretch_ros2/blob/dca394dfad124281cbf3ceaa373b81f2266f1cb4/stretch_core/launch/navigation_camera.launch.py) for use case example.

This PR also adds the following launch files:
- [navigation_camera.launch.py](https://github.com/hello-robot/stretch_ros2/blob/dca394dfad124281cbf3ceaa373b81f2266f1cb4/stretch_core/launch/navigation_camera.launch.py) 
- [old_gripper_camera.launch.py](https://github.com/hello-robot/stretch_ros2/blob/dca394dfad124281cbf3ceaa373b81f2266f1cb4/stretch_core/launch/old_gripper_camera.launch.py)

### CODE REVIEW

**Comment by hello-binit** [comment]
Hi @hello-fazil, thanks for opening this PR. What is the frame rate I should expect from the beta teleop cameras? I'm seeing 1-3hz in my testing. With the `stretch_camera_streams_check.py --usb_cam_port /dev/hello-gripper-camera` tool, I'm seeing near real-time imagery, so I suspect there's a bottleneck at the ROS layer for some reason.

**Review by hello-binit — CHANGES_REQUESTED** [review]
See comment above.

**Comment by hello-fazil** [comment]
> Hi @hello-fazil, thanks for opening this PR. What is the frame rate I should expect from the beta teleop cameras? I'm seeing 1-3hz in my testing. With the `stretch_camera_streams_check.py --usb_cam_port /dev/hello-gripper-camera` tool, I'm seeing near real-time imagery, so I suspect there's a bottleneck at the ROS layer for some reason. 

Hi @hello-binit , was the lag you mentioned observed while viewing the camera stream through the RQT image viewer or a Rviz camera view?  If so, even I have been facing that lag while visualizing in rviz or rqt, which I suspect is to do something with the ROS layer and having a subscriber overhead. This [thread](https://www.reddit.com/r/ROS/comments/e7pdhq/ros_high_latency_issues_when_streaming_video_or/) suggests that likely the high network traffic within the NUC could cause this behavior. 

But from my testing, functionally, I don't see this lag happening if I use a [simple Python node to subscribe to the camera image topic](https://gist.github.com/hello-fazil/bee106b7f22dd5a89f00ba43bddbe28a) and display it in real-time using cv2.imshow(), which produces real-time imagery similar to the tool `stretch_camera_streams_check.py`. I have added a `print_debug` param that will print the average stream latency, which could help us profile the lags between reading the frames from the USB port. 
I profiled these three cameras,
- The new Navigation Camera (Arducam OV9782), I get 31.88 ms lag or 31.37 Hz
- Older Gripper Camera (Vendor is JY--Camera), I got 33.52 ms lag or 29.83 Hz. 
- Arducam 1080p 12mp HD Camera, I got a high 60.48 ms lag or 16.53 Hz 

@hello-binit  @hello-vinitha
I would recommend you try out the below steps to verify if the camera is functionally streaming without lag and you are able to visualize it using a subscriber without lag:
Start the gripper camera stream with print_debug, which will keep printing the average latency measured:
```
ros2 launch stretch_core beta_gripper_camera.launch.py print_debug:=True
```

Download this script [ros2_simple_image_subscriber.py](https://gist.github.com/hello-fazil/bee106b7f22dd5a89f00ba43bddbe28a) and run it to display the camera stream from the gripper:
```
python3 ros2_simple_image_subscriber.py --ros-args -p camera_topic:=/gripper_camera/image_raw
```

What latencies were reported, and did the imagery from the subscriber node feel real-time?

**Comment by hello-vinitha** [comment]
@hello-fazil I followed your instructions and did not see any noticeable lag with the gripper camera. The average latency was 123.7ms and average frequency was 8.08 Hz

**Pull request merged**
