### PR TITLE
Add stow service to Humble

### PR DESCRIPTION
**Pull request by hello-atharva**
## Summary

This feature adds a stowing service to `stretch_driver`. It utilizes the `robot.stow()` method provided by Stretch Body.

## How-to-test
In a terminal, run
```
ros2 launch stretch_core stretch_driver.launch.py
```
In a separate terminal, run
```
ros2 service call /stow_the_robot std_srvs/srv/Trigger
```

### CODE REVIEW

**Comment by hello-binit** [comment]
Thanks for opening this PR @hello-atharva. I recently merged https://github.com/hello-robot/stretch_ros/pull/105, which fixed a couple bugs with the stow service in Stretch ROS1. Can you port over the improvements/bugfixes/docs of that PR to ROS2?

**Comment by hello-atharva** [comment]
@hello-binit Sounds good! Can we pull the changes from this PR and have a new one for porting the additional bug fixes from ROS 1?

**Comment by hello-binit** [comment]
Yes, sounds good. Can you change the base branch from rolling to humble?

**Comment by hello-atharva** [comment]
Done!

**Review by hello-chintan — APPROVED** [review]

**Pull request merged**
