### PR TITLE
FUNMAP port to ROS 2

### PR DESCRIPTION
**Pull request by hello-atharva**
## Summary
This PR adds a ROS 2 version of FUNMAP to the `rolling` branch.

## How to test

Include `funmap.launch.py` in your launch file along with `stretch_driver` (boardcast odom tf must be set to true) and `d435i_high_resolution`. Additionally, you can also launch keyboard teleop to test `odom` to `map` transforms

### CODE REVIEW

**Comment by hello-binit** [comment]
Hey @hello-atharva , can you add me as a reviewer?

**Comment by hello-atharva** [comment]
@hello-binit Added you as a reviewer

**Review by hello-binit — APPROVED** [review]
Approved, will do deeper review as part of ROS2 MVP release.

**Review by hello-chintan — APPROVED** [review]

**Comment by hello-atharva** [comment]
Do we need to update the target branch to `humble`?

**Comment by hello-chintan** [comment]
@hello-atharva Ah, yes! Good catch.

**Comment by hello-atharva** [comment]
Changed base to `humble`

**Pull request merged**
